version: '3.8'

services:
  aonsoku:
    container_name: aonsoku
    image: ghcr.io/victoralvesf/aonsoku:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      # When it's true AND SERVER_URL is set, only username and password will be visible on login.
      # - HIDE_SERVER=true
      # - SERVER_URL=http://address:port
