export default function handleError(error: Error | string, throwError?: boolean) {
    const errorMessage = error?.reason?.reason || error?.reason || error.toString();

    console.error("[FocalMK] Fatal error occured: ", errorMessage);

    // Show message box if in igniteView
    if (window.igniteView?.commandBridge?.displayError) {
        window.igniteView.commandBridge.displayError("Something went wrong with audio playback", errorMessage);
    }

    if (throwError) {
        throw new Error(errorMessage);
    }
}

export const errorNames = {
    INVALID_ERROR_ID: "INVALID_ERROR_ID",
    INVALID_ERROR_REASON: "INVALID_ERROR_REASON",
    ACCESS_DENIED: "ACCESS_DENIED",
    AGE_GATE: "AGE_GATE",
    AUTHORIZATION_ERROR: "AUTHORIZATION_ERROR",
    BUFFER_STALLED_ERROR: "BUFFER_STALLED_ERROR",
    CONFIGURATION_ERROR: "CONFIGURATION_ERROR",
    CONTENT_EQUIVALENT: "CONTENT_EQUIVALENT",
    CONTENT_RESTRICTED: "CONTENT_RESTRICTED",
    CONTENT_UNAVAILABLE: "CONTENT_UNAVAILABLE",
    CONTENT_UNSUPPORTED: "CONTENT_UNSUPPORTED",
    DEVICE_LIMIT: "DEVICE_LIMIT",
    GEO_BLOCK: "GEO_BLOCK",
    INVALID_ARGUMENTS: "INVALID_ARGUMENTS",
    PLAYREADY_CBC_ENCRYPTION_ERROR: "PLAYREADY_CBC_ENCRYPTION_ERROR",
    MEDIA_CERTIFICATE: "MEDIA_CERTIFICATE",
    MEDIA_DESCRIPTOR: "MEDIA_DESCRIPTOR",
    MEDIA_LICENSE: "MEDIA_LICENSE",
    MEDIA_KEY: "MEDIA_KEY",
    MEDIA_PLAYBACK: "MEDIA_PLAYBACK",
    MEDIA_SESSION: "MEDIA_SESSION",
    NETWORK_ERROR: "NETWORK_ERROR",
    NOT_FOUND: "NOT_FOUND",
    NOT_IMPLEMENTED: "NOT_IMPLEMENTED",
    PARSE_ERROR: "PARSE_ERROR",
    PLAY_ACTIVITY: "PLAY_ACTIVITY",
    REQUEST_ERROR: "REQUEST_ERROR",
    QUOTA_EXCEEDED: "QUOTA_EXCEEDED",
    SERVER_ERROR: "SERVER_ERROR",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
    STREAM_UPSELL: "STREAM_UPSELL",
    SUBSCRIPTION_ERROR: "SUBSCRIPTION_ERROR",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    UNAUTHORIZED_ERROR: "UNAUTHORIZED_ERROR",
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
    UNSUPPORTED_ERROR: "UNSUPPORTED_ERROR",
    USER_INTERACTION_REQUIRED: "USER_INTERACTION_REQUIRED",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    OUTPUT_RESTRICTED: "OUTPUT_RESTRICTED",
    WIDEVINE_CDM_EXPIRED: "WIDEVINE_CDM_EXPIRED"
}

export const ERROR_CODES: Record<string, string> = {
    "-1003": errorNames.MEDIA_LICENSE,
    "-1004": errorNames.DEVICE_LIMIT,
    "-1017": errorNames.GEO_BLOCK,
    "1010": errorNames.NOT_FOUND,
    "2002": errorNames.AUTHORIZATION_ERROR,
    "2034": errorNames.TOKEN_EXPIRED,
    "3059": errorNames.DEVICE_LIMIT,
    "3063": errorNames.SUBSCRIPTION_ERROR,
    "3076": errorNames.CONTENT_UNAVAILABLE,
    "3082": errorNames.CONTENT_RESTRICTED,
    "3084": errorNames.STREAM_UPSELL,
    "5002": errorNames.SERVER_ERROR,
    "180202": errorNames.PLAYREADY_CBC_ENCRYPTION_ERROR,
    "190121": errorNames.WIDEVINE_CDM_EXPIRED
}